### ISSUE TITLE
latest develop branch can't build on windows

### ISSUE THREAD

**Issue by javametro** [shiguredo/momo#367]
-- Build files have been written to: D:/momo/_build/windows_x86_64/release/momo
  ayame_client.cpp
D:\momo\src\rtc\rtc_manager.h(7,10): error C1083: Cannot open include file: 'api/environment/environment_factory.h': No such file or directory [D:\momo\_bui
ld\windows_x86_64\release\momo\momo.vcxproj]
  (compiling source file '../../../../src/ayame/ayame_client.cpp')

  main.cpp
D:\momo\src\rtc\rtc_manager.h(7,10): error C1083: Cannot open include file: 'api/environment/environment_factory.h': No such file or directory [D:\momo\_bui
ld\windows_x86_64\release\momo\momo.vcxproj]
  (compiling source file '../../../../src/main.cpp')

  metrics_server.cpp
D:\momo\src\rtc\rtc_manager.h(7,10): error C1083: Cannot open include file: 'api/environment/environment_factory.h': No such file or directory [D:\momo\_bui
ld\windows_x86_64\release\momo\momo.vcxproj]
  (compiling source file '../../../../src/metrics/metrics_server.cpp')

  metrics_session.cpp
D:\momo\src\rtc\rtc_manager.h(7,10): error C1083: Cannot open include file: 'api/environment/environment_factory.h': No such file or directory [D:\momo\_bui
ld\windows_x86_64\release\momo\momo.vcxproj]
  (compiling source file '../../../../src/metrics/metrics_session.cpp')

  momo_version.cpp
  p2p_server.cpp
D:\momo\src\rtc\rtc_manager.h(7,10): error C1083: Cannot open include file: 'api/environment/environment_factory.h': No such file or directory [D:\momo\_bui
ld\windows_x86_64\release\momo\momo.vcxproj]
  (compiling source file '../../../../src/p2p/p2p_server.cpp')

  p2p_session.cpp
D:\momo\src\rtc\rtc_manager.h(7,10): error C1083: Cannot open include file: 'api/environment/environment_factory.h': No such file or directory [D:\momo\_bui
ld\windows_x86_64\release\momo\momo.vcxproj]
  (compiling source file '../../../../src/p2p/p2p_session.cpp')

  p2p_websocket_session.cpp
D:\momo\src\rtc\rtc_manager.h(7,10): error C1083: Cannot open include file: 'api/environment/environment_factory.h': No such file or directory [D:\momo\_bui
ld\windows_x86_64\release\momo\momo.vcxproj]
  (compiling source file '../../../../src/p2p/p2p_websocket_session.cpp')

  aligned_encoder_adapter.cpp
  device_video_capturer.cpp
  momo_video_decoder_factory.cpp
D:\momo\src\rtc\momo_video_decoder_factory.h(8,10): error C1083: Cannot open include file: 'api/environment/environment.h': No such file or directory [D:\mo
mo\_build\windows_x86_64\release\momo\momo.vcxproj]
  (compiling source file '../../../../src/rtc/momo_video_decoder_factory.cpp')

  momo_video_encoder_factory.cpp
D:\momo\src\rtc\momo_video_encoder_factory.h(8,10): error C1083: Cannot open include file: 'api/environment/environment.h': No such file or directory [D:\mo
mo\_build\windows_x86_64\release\momo\momo.vcxproj]
  (compiling source file '../../../../src/rtc/momo_video_encoder_factory.cpp')

  native_buffer.cpp
  peer_connection_observer.cpp
  rtc_connection.cpp
  rtc_manager.cpp
D:\momo\src\rtc\rtc_manager.h(7,10): error C1083: Cannot open include file: 'api/environment/environment_factory.h': No such file or directory [D:\momo\_bui
ld\windows_x86_64\release\momo\momo.vcxproj]
  (compiling source file '../../../../src/rtc/rtc_manager.cpp')

  rtc_ssl_verifier.cpp
  serial_data_channel.cpp
  serial_data_manager.cpp
  open_h264_video_encoder.cpp
D:\momo\src\sora-cpp-sdk\src\open_h264_video_encoder.cpp(34,10): error C1083: Cannot open include file: 'api/environment/environment_factory.h': No such fil
e or directory [D:\momo\_build\windows_x86_64\release\momo\momo.vcxproj]
  Generating Code...
  Compiling...
  scalable_track_source.cpp
  sora_client.cpp
D:\momo\src\rtc\rtc_manager.h(7,10): error C1083: Cannot open include file: 'api/environment/environment_factory.h': No such file or directory [D:\momo\_bui
ld\windows_x86_64\release\momo\momo.vcxproj]
  (compiling source file '../../../../src/sora/sora_client.cpp')

  sora_server.cpp
D:\momo\src\rtc\rtc_manager.h(7,10): error C1083: Cannot open include file: 'api/environment/environment_factory.h': No such file or directory [D:\momo\_bui
ld\windows_x86_64\release\momo\momo.vcxproj]
  (compiling source file '../../../../src/sora/sora_server.cpp')

  sora_session.cpp
D:\momo\src\rtc\rtc_manager.h(7,10): error C1083: Cannot open include file: 'api/environment/environment_factory.h': No such file or directory [D:\momo\_bui
ld\windows_x86_64\release\momo\momo.vcxproj]
  (compiling source file '../../../../src/sora/sora_session.cpp')

  ssl_verifier.cpp
  util.cpp
D:\momo\src\momo_args.h(12,10): error C1083: Cannot open include file: 'rtc_base/crypt_string_revive.h': No such file or directory [D:\momo\_build\windows_x
86_64\release\momo\momo.vcxproj]
  (compiling source file '../../../../src/util.cpp')

  watchdog.cpp
  websocket.cpp
D:\momo\src\momo_args.h(12,10): error C1083: Cannot open include file: 'rtc_base/crypt_string_revive.h': No such file or directory [D:\momo\_build\windows_x
86_64\release\momo\momo.vcxproj]
  (compiling source file '../../../../src/websocket.cpp')

  sdl_renderer.cpp
  screen_video_capturer.cpp
  nvcodec_video_encoder.cpp
  NvEncoder.cpp
  NvEncoderD3D11.cpp
  nvcodec_video_decoder.cpp
  vpl_session_impl.cpp
  vpl_video_decoder.cpp
  vpl_video_encoder.cpp
  Generating Code...
DEBUG:root:popd D:\momo <-- D:\momo\_build\windows_x86_64\release\momo
Traceback (most recent call last):
  File "D:\momo\run.py", line 604, in <module>
    main()
  File "D:\momo\run.py", line 534, in main
    cmd(
  File "D:\momo\buildbase.py", line 75, in cmd
    return subprocess.run(args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stephen\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['D:\\momo\\_install\\windows_x86_64\\release\\cmake\\bin\\cmake.EXE', '--build', '.', '-j16', '--config', 'Release']' returned non-zero exit status 1.

**Comment by javametro** [comment]
commit caa4f3121a430a3a1248b1c572f9a838ef566c0a
